name: Publish Docker And Auto Release

on:
  push:
    branches:
      - release
jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PUB_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PUB_DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: debugicu/excalidraw_zh:latest
